
image:
  file: .gitpod.Dockerfile


tasks:
  - name: "make two task"
    command: |
      echo "第一行"
      echo "第二行"
      pwd
      exit
  
  - name: "star our db and to some test"
    command: |
      /bin/bash /workspace/To_be_deleted/star_db.sh
      exit
vscode:
  extensions:
    - ms-python.python